#! /bin/bash

printargs(){ 
	while [ $# -gt 0 ]; do 
		echo "$1"
		shift
	done 
}

if [ "$1" == "--no-ls" ]; then
	shift
else
	echo ll2lpath: >&2
	ll2lpath "$@"
fi

#echo lsdups arguments:
#printargs "$@"
#echo .
#exit


if [ $# == 0 ]; then
	wd=.files
	mkdir -p "$wd"
else
	wd="$1"
	shift
fi

files="$(ls -1 "$wd"/20*-files "$wd"/19*-files "$wd"/21*-files 2>/dev/null | sort -r | head -n 1)"
[ -z "$files" ] && echo lsdups: can not get files file >&2 && exit 1

#printargs "$files" "$wd"/hashes 

runcpp -o '-std=gnu++11 -O3' lsdups-internal.cpp "$files" "$wd"/hashes > "$wd"/rmdups.bash || { echo rmdups not created; exit 1; }
chmod +x "$wd"/rmdups.bash

if [ ! -f "$wd"/rmdups-persist ]; then
	if [ -s "$wd"/rmdups.bash ]; then  
		echo lsdups: "$wd"/rmdups-persist не создан
		grep '^\(f(){ #====\|#----\)' "$wd"/rmdups.bash
	else
		echo дублирующиеся файлы отсутствуют
	fi
else
	if [ "$(	diff -u3 "$wd"/rmdups-persist "$wd"/rmdups )" != "" ]; then
		echo lsdups: Изменеия в дубликатах по сравнению с .files/rmdups-persist \
\( $(	diff -u3 "$wd"/rmdups-persist "$wd"/rmdups.bash | wc -l ) \):
		diff -u3 <(grep '^\(f(){ #====\|#----\)' "$wd"/rmdups-persist) <(grep '^\(f(){ #====\|#----\)' "$wd"/rmdups.bash) | 
			grep -v '^\(+++\|---\)'
	else
		echo ИЗМЕНЕНИЙ НЕТ
		grep '^\(f(){ #====\|#----\)' "$wd"/rmdups.bash
	fi
fi
