#! /bin/bash

usage(){
    echo nthline - read text and print nth line with prefix >&2
    echo usage: nthline [-n N] [-p prefix] >&2
    echo defaults: N=100 prefix=\"\" >&2
    exit $1
}

N=100
prefix=""
oneline=0
while getopts n:p:h1 opts ; do
    case $opts in
	n) N=$OPTARG
	   ;;
	p) prefix="$OPTARG"
	   ;;
	1) oneline=1
	   N=1
	   ;;
	h) usage 0
	   ;;
	*) usage 1
	   ;;
    esac
done

I=0
while read line; do
    I=$(($I + 1))
    if [ $I == $N ]; then
	if [ $oneline == 1 ] ; then
	    tput sc
	    echo -n "$(tput setf 2)$prefix $line"
	    tput el
	    tput rc
	else
	    echo "$prefix $line"
	fi
	I=0
    fi
done
