#! /bin/bash

usage(){
    echo nthline - read text and print nth line with prefix >&2
    echo usage: nthline [-n N] [-p prefix] >&2
    echo defaults: N=100 prefix=\"\" >&2
    exit $1
}

N=100
prefix=""
oneline=0
color=-1
while getopts n:p:h1c: opts ; do
    case $opts in
	n) N=$OPTARG
	   ;;
	p) prefix="$OPTARG"
	   ;;
	1) oneline=1
	   ;;
	h) usage 0
	   ;;
	c) color="$OPTARG"
	   ;;
	*) usage 1
	   ;;
    esac
done

[ $oneline == 1 ] && tput civis
I=0
while read line; do
    if [ $oneline == 1 ] ; then
	tput sc
	[ $color != -1 ] && tput setf $color
	echo -n "${line:0:$(( $(tput cols) - 2))}"
	tput el
	tput rc
    fi
    I=$(($I + 1))
    if [ $I == $N ]; then
	echo "$prefix $line"
	I=0
    fi
done
[ $oneline == 1 ] && echo $(tput cnorm)
