#! /bin/bash

recursive_rm(){
	local dir="$1"
	if [ "$dir" != "." -a "$(ls -A "$dir")" == "" ]; then
		rmdir "$dir"
		[ "${dir%/*}" != "$dir" ] && recursive_rm "${dir%/*}"
		echo mkdir \""$(echo "$start_path$dir" | sed 's/"/\\"/g;s/\$/\\\$/g')"\"
	fi
}

cycle(){	
if [ "$1" == "" ]; then
	start_path=
else
	start_path="${1%/}/"
	cd "$start_path"
	[ $? != 0 ] && exit 1
fi

dir=
after_dir=0
while read line ; do 
	if [ $after_dir == 1 ]; then
		if [ "$line" == "" ]; then
			recursive_rm "$dir"
		fi
		after_dir=0
	fi
	if [ "${line#./}" != "$line" ]; then
		dir="${line%:}"
		after_dir=1
	fi
done < <(ls -ALR)
if [ $after_dir == 1 ]; then
	recursive_rm "$dir"
fi

if [ "$1" != "" ]; then
	cd - >/dev/null
	if [ "$(ls -A "$start_path")" == "" ]; then
		rmdir "$start_path"
		echo mkdir \""$(echo "$start_path" | sed 's/"/\\"/g;s/\$/\\\$/g')"\"
	fi
fi
}

cycle "$1" | sort
